version: '3'

services:

  db:
    image: mysql:8.0.2
    restart: always
    user: mysql
    environment:
      MYSQL_ROOT_PASSWORD: 1111
      MYSQL_DATABASE: dsr_db
    ports:
      - 3306:3306

  web:
    build: ./backend
    command: sh start.sh
    ports:
      - 8888:8888
    volumes:
      - ./backend:/var/www/backend
    links:
      - db
    depends_on:
      - db

  front:
    build: ./frontend-react
    command: npm start
    ports:
      - 3000:3000
    volumes:
      - ./frontend-react:/var/www/frontend
    depends_on:
      - web

